Update uat.yaml

diff --git a/.github/workflows/uat.yaml b/.github/workflows/uat.yaml
--- a/.github/workflows/uat.yaml
+++ b/.github/workflows/uat.yaml
@@ -30,7 +30,10 @@ jobs:
       run: |
           echo "node -v"
           node -v
-          if [[ "${{ github.ref }}" == "refs/heads/uat2" ]]; then
+          if [[ "${GITHUB_REF}" != "refs/heads/abcd" ]]; then
+            echo "Error: This pipeline should only run on the 'uat2' branch."
+            exit 1  # Fail the job if the ref is not 'uat2'
+          fi
 
           echo AWSCLOUDFORMATIONCONFIG="{\
           \"configLevel\":\"project\",\
